twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Infrastructure\Shared\Twig\Components\: 'components/'
        App\Infrastructure\Shared\Twig\Components\Alert\: 'components/alert.html.twig'
